version: '3.7'

services:
  signalrechoserver:
    container_name: signalrechoserver
    image: signalrechoserver:latest
    hostname: signalrechoserver
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5128
    ports:
      - 5128:5128
    # networks:
    #   - swapnet
    network_mode: host